# This workflow installs Ruby, installs gems, and runs tests.
name: "Ruby Gem CI"
on:
  push:
  pull_request:

jobs:
  rspec:
    name: "rspec (Ruby ${{ matrix.ruby-version }})"
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        ruby-version: ['2.3', '2.4', '2.5', '2.6']

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install PhantomJS
        run: |
          export PHANTOMJS_VERSION='2.1.1'
          export PHANTOMJS_URL="https://github.com/Medium/phantomjs/releases/download/v${PHANTOMJS_VERSION}/phantomjs-${PHANTOMJS_VERSION}-linux-x86_64.tar.bz2"
          wget -q ${PHANTOMJS_URL}
          tar xfj phantomjs-${PHANTOMJS_VERSION}-linux-x86_64.tar.bz2 --wildcards */bin/phantomjs --strip-components=2
          sudo mv phantomjs /usr/local/bin/phantomjs
          phantomjs --version

      - name: Install Ruby and gems
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          bundler-cache: true
          bundler: '< 2'

      - name: rspec
        run: bundle exec rspec spec
